language: node_js
node_js:
- "0.10"
before_install:
before_script:
  - npm install -g grunt-cli
  - npm install -g codeclimate-test-reporter
  - npm install -d
branches:
  only:
    - master
script:
  - grunt jasmine:all
after_success:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov/lcov.info
